PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS Docgia (
  MaDocGia TEXT PRIMARY KEY,
  HoLot TEXT NOT NULL,
  Ten TEXT NOT NULL,
  NgaySinh TEXT,
  Phai TEXT,
  DiaChi TEXT,
  DienThoai TEXT,
  Email TEXT UNIQUE,
  Password TEXT
);

CREATE TABLE IF NOT EXISTS NhaXuatBan (
  MaNXB TEXT PRIMARY KEY,
  TenNXB TEXT NOT NULL,
  DiaChi TEXT
);

CREATE TABLE IF NOT EXISTS Sach (
  MaSach TEXT PRIMARY KEY,
  TenSach TEXT NOT NULL,
  DonGia REAL DEFAULT 0,
  SoQuyen INTEGER DEFAULT 0,
  NamXuatBan INTEGER,
  MaNXB TEXT,
  NguonGoc TEXT,
  MoTa TEXT,
  TheLoai TEXT,
  AnhBia TEXT,
  FOREIGN KEY (MaNXB) REFERENCES NhaXuatBan(MaNXB)
);

CREATE TABLE IF NOT EXISTS TheoDoiMuonSach (
  MaMuon INTEGER PRIMARY KEY AUTOINCREMENT,
  MaDocGia TEXT NOT NULL,
  MaSach TEXT NOT NULL,
  NgayMuon TEXT NOT NULL,
  NgayTra TEXT,
  HanTra TEXT,
  TrangThai TEXT DEFAULT 'dang_muon',
  FOREIGN KEY (MaDocGia) REFERENCES Docgia(MaDocGia),
  FOREIGN KEY (MaSach) REFERENCES Sach(MaSach)
);

CREATE TABLE IF NOT EXISTS NhanVien (
  MSNV TEXT PRIMARY KEY,
  HoTenNV TEXT NOT NULL,
  Password TEXT NOT NULL,
  ChucVu TEXT,
  DiaChi TEXT,
  SoDienThoai TEXT,
  Email TEXT UNIQUE
);

CREATE TABLE IF NOT EXISTS OTPToken (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  email TEXT NOT NULL,
  otp TEXT NOT NULL,
  role TEXT NOT NULL,
  expiresAt INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS DanhGiaSach (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  MaDocGia TEXT,
  MaSach TEXT,
  Diem INTEGER CHECK(Diem BETWEEN 1 AND 5),
  BinhLuan TEXT,
  NgayDanhGia TEXT DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (MaDocGia) REFERENCES Docgia(MaDocGia),
  FOREIGN KEY (MaSach) REFERENCES Sach(MaSach)
);
